name = "natural"
defaultTargets = ["Natural"]

[[require]]
name = "aesop"
scope = "leanprover-community"
rev = "master"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[lean_lib]]
name = "Natural"
